//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.04 at 08:06:28 PM EDT 
//


package com.softexpert.integration.wsdl.forms;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for newTableRecordListRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="newTableRecordListRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="UserID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TableID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FormRecordList" type="{urn:form}FormRecordList"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "newTableRecordList")
@XmlType(name = "newTableRecordListRequestType", propOrder = {

})
public class NewTableRecordListRequestType {

    @XmlElement(name = "UserID", required = true)
    protected String userID;
    @XmlElement(name = "TableID", required = true)
    protected String tableID;
    @XmlElement(name = "FormRecordList", required = true)
    protected FormRecordList formRecordList;

    /**
     * Gets the value of the userID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserID(String value) {
        this.userID = value;
    }

    /**
     * Gets the value of the tableID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTableID() {
        return tableID;
    }

    /**
     * Sets the value of the tableID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTableID(String value) {
        this.tableID = value;
    }

    /**
     * Gets the value of the formRecordList property.
     * 
     * @return
     *     possible object is
     *     {@link FormRecordList }
     *     
     */
    public FormRecordList getFormRecordList() {
        return formRecordList;
    }

    /**
     * Sets the value of the formRecordList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormRecordList }
     *     
     */
    public void setFormRecordList(FormRecordList value) {
        this.formRecordList = value;
    }

}
