//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.04 at 08:06:28 PM EDT 
//


package com.softexpert.integration.wsdl.forms;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.softexpert.integration.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NewTableRecord_QNAME = new QName("urn:form", "newTableRecord");
    private final static QName _NewTableRecordResponse_QNAME = new QName("urn:form", "newTableRecordResponse");
    private final static QName _GetTableRecord_QNAME = new QName("urn:form", "getTableRecord");
    private final static QName _GetTableRecordResponse_QNAME = new QName("urn:form", "getTableRecordResponse");
    private final static QName _EditTableRecord_QNAME = new QName("urn:form", "editTableRecord");
    private final static QName _EditTableRecordResponse_QNAME = new QName("urn:form", "editTableRecordResponse");
    private final static QName _DeleteTableRecord_QNAME = new QName("urn:form", "deleteTableRecord");
    private final static QName _DeleteTableRecordResponse_QNAME = new QName("urn:form", "deleteTableRecordResponse");
    private final static QName _NewTableRecordList_QNAME = new QName("urn:form", "newTableRecordList");
    private final static QName _NewTableRecordListResponse_QNAME = new QName("urn:form", "newTableRecordListResponse");
    private final static QName _DeleteTableRecordList_QNAME = new QName("urn:form", "deleteTableRecordList");
    private final static QName _DeleteTableRecordListResponse_QNAME = new QName("urn:form", "deleteTableRecordListResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.softexpert.integration.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NewTableRecordRequestType }
     * 
     */
    public NewTableRecordRequestType createNewTableRecordRequestType() {
        return new NewTableRecordRequestType();
    }

    /**
     * Create an instance of {@link NewTableRecordResponseType }
     * 
     */
    public NewTableRecordResponseType createNewTableRecordResponseType() {
        return new NewTableRecordResponseType();
    }

    /**
     * Create an instance of {@link GetTableRecordRequestType }
     * 
     */
    public GetTableRecordRequestType createGetTableRecordRequestType() {
        return new GetTableRecordRequestType();
    }

    /**
     * Create an instance of {@link GetTableRecordResponseType }
     * 
     */
    public GetTableRecordResponseType createGetTableRecordResponseType() {
        return new GetTableRecordResponseType();
    }

    /**
     * Create an instance of {@link EditTableRecordRequestType }
     * 
     */
    public EditTableRecordRequestType createEditTableRecordRequestType() {
        return new EditTableRecordRequestType();
    }

    /**
     * Create an instance of {@link EditTableRecordResponseType }
     * 
     */
    public EditTableRecordResponseType createEditTableRecordResponseType() {
        return new EditTableRecordResponseType();
    }

    /**
     * Create an instance of {@link DeleteTableRecordRequestType }
     * 
     */
    public DeleteTableRecordRequestType createDeleteTableRecordRequestType() {
        return new DeleteTableRecordRequestType();
    }

    /**
     * Create an instance of {@link DeleteTableRecordResponseType }
     * 
     */
    public DeleteTableRecordResponseType createDeleteTableRecordResponseType() {
        return new DeleteTableRecordResponseType();
    }

    /**
     * Create an instance of {@link NewTableRecordListRequestType }
     * 
     */
    public NewTableRecordListRequestType createNewTableRecordListRequestType() {
        return new NewTableRecordListRequestType();
    }

    /**
     * Create an instance of {@link NewTableRecordListResponseType }
     * 
     */
    public NewTableRecordListResponseType createNewTableRecordListResponseType() {
        return new NewTableRecordListResponseType();
    }

    /**
     * Create an instance of {@link DeleteTableRecordListRequestType }
     * 
     */
    public DeleteTableRecordListRequestType createDeleteTableRecordListRequestType() {
        return new DeleteTableRecordListRequestType();
    }

    /**
     * Create an instance of {@link DeleteTableRecordListResponseType }
     * 
     */
    public DeleteTableRecordListResponseType createDeleteTableRecordListResponseType() {
        return new DeleteTableRecordListResponseType();
    }

    /**
     * Create an instance of {@link FieldData }
     * 
     */
    public FieldData createFieldData() {
        return new FieldData();
    }

    /**
     * Create an instance of {@link FieldFileData }
     * 
     */
    public FieldFileData createFieldFileData() {
        return new FieldFileData();
    }

    /**
     * Create an instance of {@link RelationshipFieldData }
     * 
     */
    public RelationshipFieldData createRelationshipFieldData() {
        return new RelationshipFieldData();
    }

    /**
     * Create an instance of {@link RelationshipArray }
     * 
     */
    public RelationshipArray createRelationshipArray() {
        return new RelationshipArray();
    }

    /**
     * Create an instance of {@link TableFieldArray }
     * 
     */
    public TableFieldArray createTableFieldArray() {
        return new TableFieldArray();
    }

    /**
     * Create an instance of {@link RelatedToData }
     * 
     */
    public RelatedToData createRelatedToData() {
        return new RelatedToData();
    }

    /**
     * Create an instance of {@link TableFieldFileArray }
     * 
     */
    public TableFieldFileArray createTableFieldFileArray() {
        return new TableFieldFileArray();
    }

    /**
     * Create an instance of {@link RelationshipListArray }
     * 
     */
    public RelationshipListArray createRelationshipListArray() {
        return new RelationshipListArray();
    }

    /**
     * Create an instance of {@link TableRecordArray }
     * 
     */
    public TableRecordArray createTableRecordArray() {
        return new TableRecordArray();
    }

    /**
     * Create an instance of {@link TableRecordListArray }
     * 
     */
    public TableRecordListArray createTableRecordListArray() {
        return new TableRecordListArray();
    }

    /**
     * Create an instance of {@link RelationshipFieldListArray }
     * 
     */
    public RelationshipFieldListArray createRelationshipFieldListArray() {
        return new RelationshipFieldListArray();
    }

    /**
     * Create an instance of {@link RelationshipArrayList }
     * 
     */
    public RelationshipArrayList createRelationshipArrayList() {
        return new RelationshipArrayList();
    }

    /**
     * Create an instance of {@link RelationshipListFieldData }
     * 
     */
    public RelationshipListFieldData createRelationshipListFieldData() {
        return new RelationshipListFieldData();
    }

    /**
     * Create an instance of {@link RecordRelationshipData }
     * 
     */
    public RecordRelationshipData createRecordRelationshipData() {
        return new RecordRelationshipData();
    }

    /**
     * Create an instance of {@link RecordRelationship }
     * 
     */
    public RecordRelationship createRecordRelationship() {
        return new RecordRelationship();
    }

    /**
     * Create an instance of {@link Record }
     * 
     */
    public Record createRecord() {
        return new Record();
    }

    /**
     * Create an instance of {@link RecordListArray }
     * 
     */
    public RecordListArray createRecordListArray() {
        return new RecordListArray();
    }

    /**
     * Create an instance of {@link TbRecord }
     * 
     */
    public TbRecord createTbRecord() {
        return new TbRecord();
    }

    /**
     * Create an instance of {@link FormRecordList }
     * 
     */
    public FormRecordList createFormRecordList() {
        return new FormRecordList();
    }

    /**
     * Create an instance of {@link RecordsResultArray }
     * 
     */
    public RecordsResultArray createRecordsResultArray() {
        return new RecordsResultArray();
    }

    /**
     * Create an instance of {@link DeleteRecordList }
     * 
     */
    public DeleteRecordList createDeleteRecordList() {
        return new DeleteRecordList();
    }

    /**
     * Create an instance of {@link DeleteRecordsResultArray }
     * 
     */
    public DeleteRecordsResultArray createDeleteRecordsResultArray() {
        return new DeleteRecordsResultArray();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NewTableRecordRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NewTableRecordRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:form", name = "newTableRecord")
    public JAXBElement<NewTableRecordRequestType> createNewTableRecord(NewTableRecordRequestType value) {
        return new JAXBElement<NewTableRecordRequestType>(_NewTableRecord_QNAME, NewTableRecordRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NewTableRecordResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NewTableRecordResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:form", name = "newTableRecordResponse")
    public JAXBElement<NewTableRecordResponseType> createNewTableRecordResponse(NewTableRecordResponseType value) {
        return new JAXBElement<NewTableRecordResponseType>(_NewTableRecordResponse_QNAME, NewTableRecordResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTableRecordRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetTableRecordRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:form", name = "getTableRecord")
    public JAXBElement<GetTableRecordRequestType> createGetTableRecord(GetTableRecordRequestType value) {
        return new JAXBElement<GetTableRecordRequestType>(_GetTableRecord_QNAME, GetTableRecordRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTableRecordResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetTableRecordResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:form", name = "getTableRecordResponse")
    public JAXBElement<GetTableRecordResponseType> createGetTableRecordResponse(GetTableRecordResponseType value) {
        return new JAXBElement<GetTableRecordResponseType>(_GetTableRecordResponse_QNAME, GetTableRecordResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EditTableRecordRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link EditTableRecordRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:form", name = "editTableRecord")
    public JAXBElement<EditTableRecordRequestType> createEditTableRecord(EditTableRecordRequestType value) {
        return new JAXBElement<EditTableRecordRequestType>(_EditTableRecord_QNAME, EditTableRecordRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EditTableRecordResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link EditTableRecordResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:form", name = "editTableRecordResponse")
    public JAXBElement<EditTableRecordResponseType> createEditTableRecordResponse(EditTableRecordResponseType value) {
        return new JAXBElement<EditTableRecordResponseType>(_EditTableRecordResponse_QNAME, EditTableRecordResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteTableRecordRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DeleteTableRecordRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:form", name = "deleteTableRecord")
    public JAXBElement<DeleteTableRecordRequestType> createDeleteTableRecord(DeleteTableRecordRequestType value) {
        return new JAXBElement<DeleteTableRecordRequestType>(_DeleteTableRecord_QNAME, DeleteTableRecordRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteTableRecordResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DeleteTableRecordResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:form", name = "deleteTableRecordResponse")
    public JAXBElement<DeleteTableRecordResponseType> createDeleteTableRecordResponse(DeleteTableRecordResponseType value) {
        return new JAXBElement<DeleteTableRecordResponseType>(_DeleteTableRecordResponse_QNAME, DeleteTableRecordResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NewTableRecordListRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NewTableRecordListRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:form", name = "newTableRecordList")
    public JAXBElement<NewTableRecordListRequestType> createNewTableRecordList(NewTableRecordListRequestType value) {
        return new JAXBElement<NewTableRecordListRequestType>(_NewTableRecordList_QNAME, NewTableRecordListRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NewTableRecordListResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NewTableRecordListResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:form", name = "newTableRecordListResponse")
    public JAXBElement<NewTableRecordListResponseType> createNewTableRecordListResponse(NewTableRecordListResponseType value) {
        return new JAXBElement<NewTableRecordListResponseType>(_NewTableRecordListResponse_QNAME, NewTableRecordListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteTableRecordListRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DeleteTableRecordListRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:form", name = "deleteTableRecordList")
    public JAXBElement<DeleteTableRecordListRequestType> createDeleteTableRecordList(DeleteTableRecordListRequestType value) {
        return new JAXBElement<DeleteTableRecordListRequestType>(_DeleteTableRecordList_QNAME, DeleteTableRecordListRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteTableRecordListResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DeleteTableRecordListResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:form", name = "deleteTableRecordListResponse")
    public JAXBElement<DeleteTableRecordListResponseType> createDeleteTableRecordListResponse(DeleteTableRecordListResponseType value) {
        return new JAXBElement<DeleteTableRecordListResponseType>(_DeleteTableRecordListResponse_QNAME, DeleteTableRecordListResponseType.class, null, value);
    }

}
