//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.04 at 08:06:28 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:form", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.softexpert.integration.wsdl.forms;
