//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.04 at 08:06:28 PM EDT 
//


package com.softexpert.integration.wsdl.form;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RelatedToData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelatedToData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="RelatedRelationshipID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="RelatedRelationshipValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelatedToData", propOrder = {

})
public class RelatedToData {

    @XmlElement(name = "RelatedRelationshipID", required = true)
    protected String relatedRelationshipID;
    @XmlElement(name = "RelatedRelationshipValue", required = true)
    protected String relatedRelationshipValue;

    /**
     * Gets the value of the relatedRelationshipID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedRelationshipID() {
        return relatedRelationshipID;
    }

    /**
     * Sets the value of the relatedRelationshipID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedRelationshipID(String value) {
        this.relatedRelationshipID = value;
    }

    /**
     * Gets the value of the relatedRelationshipValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedRelationshipValue() {
        return relatedRelationshipValue;
    }

    /**
     * Sets the value of the relatedRelationshipValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedRelationshipValue(String value) {
        this.relatedRelationshipValue = value;
    }

}
