//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.04 at 08:06:28 PM EDT 
//


package com.softexpert.integration.wsdl.form;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TableRecordArray complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TableRecordArray"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TableFieldList" type="{urn:form}tableFieldArray" minOccurs="0"/&gt;
 *         &lt;element name="RelationshipList" type="{urn:form}relationshipListArray" minOccurs="0"/&gt;
 *         &lt;element name="TableFieldFileList" type="{urn:form}tableFieldFileArray" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TableRecordArray", propOrder = {
    "tableFieldList",
    "relationshipList",
    "tableFieldFileList"
})
public class TableRecordArray {

    @XmlElement(name = "TableFieldList")
    protected TableFieldArray tableFieldList;
    @XmlElement(name = "RelationshipList")
    protected RelationshipListArray relationshipList;
    @XmlElement(name = "TableFieldFileList")
    protected TableFieldFileArray tableFieldFileList;

    /**
     * Gets the value of the tableFieldList property.
     * 
     * @return
     *     possible object is
     *     {@link TableFieldArray }
     *     
     */
    public TableFieldArray getTableFieldList() {
        return tableFieldList;
    }

    /**
     * Sets the value of the tableFieldList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableFieldArray }
     *     
     */
    public void setTableFieldList(TableFieldArray value) {
        this.tableFieldList = value;
    }

    /**
     * Gets the value of the relationshipList property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipListArray }
     *     
     */
    public RelationshipListArray getRelationshipList() {
        return relationshipList;
    }

    /**
     * Sets the value of the relationshipList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipListArray }
     *     
     */
    public void setRelationshipList(RelationshipListArray value) {
        this.relationshipList = value;
    }

    /**
     * Gets the value of the tableFieldFileList property.
     * 
     * @return
     *     possible object is
     *     {@link TableFieldFileArray }
     *     
     */
    public TableFieldFileArray getTableFieldFileList() {
        return tableFieldFileList;
    }

    /**
     * Sets the value of the tableFieldFileList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableFieldFileArray }
     *     
     */
    public void setTableFieldFileList(TableFieldFileArray value) {
        this.tableFieldFileList = value;
    }

}
