//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.04 at 08:06:28 PM EDT 
//


package com.softexpert.integration.wsdl.form;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TbRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TbRecord"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TableFieldList" type="{urn:form}tableFieldArray"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TbRecord", propOrder = {
    "tableFieldList"
})
public class TbRecord {

    @XmlElement(name = "TableFieldList", required = true)
    protected TableFieldArray tableFieldList;

    /**
     * Gets the value of the tableFieldList property.
     * 
     * @return
     *     possible object is
     *     {@link TableFieldArray }
     *     
     */
    public TableFieldArray getTableFieldList() {
        return tableFieldList;
    }

    /**
     * Sets the value of the tableFieldList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableFieldArray }
     *     
     */
    public void setTableFieldList(TableFieldArray value) {
        this.tableFieldList = value;
    }

}
